AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to launch an EC2 web server

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-xxxxxxxxxxxxxx  # Specify the desired AMI ID
      InstanceType: t2.micro       # Specify the instance type
      SecurityGroups:
        - Ref: WebServerSecurityGroup
      KeyName: my-keypair          # Specify the SSH key pair name
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd

  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for the EC2 web server
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0     # Open HTTP access to everyone (consider restricting this)
      VpcId: vpc-xxxxxxxx      # Specify your VPC ID

Outputs:
  PublicIpAddress:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
